application: dauntless-glow-169223
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest
